# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6de3b2ec32cc9b463e78c7cad2fc8a0874711de8f4ec3f9aac5b3bc5a3d5a47f9668651d3065ef6cddb59f3ceadcf9a2ea8b8656be2c08cae4f3fc5472c87365

test:
  secret_key_base: 1b2eea857444510a52ef6787b530256e07b9322fbf86bcb0bc7cf93ac8647a3171fd9997ab4d06b926d92cf444a4603bcc779c602853090a329616111d5b1b9e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
